// Code generated by protoc-gen-go. DO NOT EDIT.
// source: int64range.proto

package pgv

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RepeatedInt64Range struct {
	Content              []int64  `protobuf:"varint,1,rep,packed,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedInt64Range) Reset()         { *m = RepeatedInt64Range{} }
func (m *RepeatedInt64Range) String() string { return proto.CompactTextString(m) }
func (*RepeatedInt64Range) ProtoMessage()    {}
func (*RepeatedInt64Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb96c25f6efe2798, []int{0}
}

func (m *RepeatedInt64Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedInt64Range.Unmarshal(m, b)
}
func (m *RepeatedInt64Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedInt64Range.Marshal(b, m, deterministic)
}
func (m *RepeatedInt64Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedInt64Range.Merge(m, src)
}
func (m *RepeatedInt64Range) XXX_Size() int {
	return xxx_messageInfo_RepeatedInt64Range.Size(m)
}
func (m *RepeatedInt64Range) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedInt64Range.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedInt64Range proto.InternalMessageInfo

func (m *RepeatedInt64Range) GetContent() []int64 {
	if m != nil {
		return m.Content
	}
	return nil
}

type RepeatedFloatRange struct {
	Content              []float32 `protobuf:"fixed32,1,rep,packed,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RepeatedFloatRange) Reset()         { *m = RepeatedFloatRange{} }
func (m *RepeatedFloatRange) String() string { return proto.CompactTextString(m) }
func (*RepeatedFloatRange) ProtoMessage()    {}
func (*RepeatedFloatRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb96c25f6efe2798, []int{1}
}

func (m *RepeatedFloatRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedFloatRange.Unmarshal(m, b)
}
func (m *RepeatedFloatRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedFloatRange.Marshal(b, m, deterministic)
}
func (m *RepeatedFloatRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedFloatRange.Merge(m, src)
}
func (m *RepeatedFloatRange) XXX_Size() int {
	return xxx_messageInfo_RepeatedFloatRange.Size(m)
}
func (m *RepeatedFloatRange) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedFloatRange.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedFloatRange proto.InternalMessageInfo

func (m *RepeatedFloatRange) GetContent() []float32 {
	if m != nil {
		return m.Content
	}
	return nil
}

type RepeatedDoubleRange struct {
	Content              []float64 `protobuf:"fixed64,1,rep,packed,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RepeatedDoubleRange) Reset()         { *m = RepeatedDoubleRange{} }
func (m *RepeatedDoubleRange) String() string { return proto.CompactTextString(m) }
func (*RepeatedDoubleRange) ProtoMessage()    {}
func (*RepeatedDoubleRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb96c25f6efe2798, []int{2}
}

func (m *RepeatedDoubleRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedDoubleRange.Unmarshal(m, b)
}
func (m *RepeatedDoubleRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedDoubleRange.Marshal(b, m, deterministic)
}
func (m *RepeatedDoubleRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedDoubleRange.Merge(m, src)
}
func (m *RepeatedDoubleRange) XXX_Size() int {
	return xxx_messageInfo_RepeatedDoubleRange.Size(m)
}
func (m *RepeatedDoubleRange) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedDoubleRange.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedDoubleRange proto.InternalMessageInfo

func (m *RepeatedDoubleRange) GetContent() []float64 {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*RepeatedInt64Range)(nil), "pgv.RepeatedInt64Range")
	proto.RegisterType((*RepeatedFloatRange)(nil), "pgv.RepeatedFloatRange")
	proto.RegisterType((*RepeatedDoubleRange)(nil), "pgv.RepeatedDoubleRange")
}

func init() { proto.RegisterFile("int64range.proto", fileDescriptor_fb96c25f6efe2798) }

var fileDescriptor_fb96c25f6efe2798 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xcc, 0x2b, 0x31,
	0x33, 0x29, 0x4a, 0xcc, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x48,
	0x2f, 0x93, 0x12, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0x20, 0xb2,
	0x4a, 0x9e, 0x5c, 0x42, 0x41, 0xa9, 0x05, 0xa9, 0x89, 0x25, 0xa9, 0x29, 0x9e, 0x20, 0x9d, 0x41,
	0x20, 0x9d, 0x42, 0xc6, 0x5c, 0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0x8c, 0x0a,
	0xcc, 0x1a, 0xcc, 0x4e, 0x92, 0xbb, 0x5e, 0x1e, 0x60, 0x16, 0x99, 0xc4, 0x28, 0xa8, 0xc4, 0xaf,
	0xc4, 0x2b, 0x90, 0xa2, 0x30, 0xe7, 0x3f, 0x14, 0x30, 0x06, 0xc1, 0x54, 0x2a, 0xb9, 0x21, 0x8c,
	0x72, 0xcb, 0xc9, 0x4f, 0x2c, 0x81, 0x18, 0x65, 0x80, 0x6a, 0x14, 0x93, 0x93, 0x18, 0xc8, 0x28,
	0xc1, 0x49, 0x8c, 0x7c, 0x4a, 0x3c, 0x5c, 0x5c, 0xa2, 0x0c, 0x0c, 0x27, 0x9c, 0x54, 0x19, 0x18,
	0x4e, 0x1c, 0x42, 0x98, 0xe3, 0xcf, 0x25, 0x0c, 0x33, 0xc7, 0x25, 0xbf, 0x34, 0x29, 0x27, 0x15,
	0x62, 0x90, 0x05, 0xaa, 0x41, 0x8c, 0x4e, 0x72, 0x20, 0x83, 0x24, 0x27, 0x31, 0x8a, 0x29, 0x89,
	0x08, 0x09, 0x09, 0x32, 0x80, 0x41, 0xa4, 0x83, 0x22, 0x94, 0x71, 0x00, 0x6e, 0x60, 0x12, 0x1b,
	0xd8, 0xab, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xf3, 0x72, 0x19, 0x1c, 0x01, 0x00,
	0x00,
}
