#!/usr/bin/env bash
p=$(cd $(dirname $BASH_SOURCE[0]); pwd -P)

showLoading() {
    mypid=$!
    loadingText=$1
    GREEN="\033[0;32m"
    NC="\033[0m"
    echo -ne "$loadingText\r"
    while kill -0 $mypid 2>/dev/null; do
        echo -ne "$loadingText.\r"
        sleep 0.5
        echo -ne "$loadingText..\r"
        sleep 0.5
        echo -ne "$loadingText...\r"
        sleep 0.5
        echo -ne "\r\033[K"
        echo -ne "$loadingText\r"
        sleep 0.5
    done
    echo -e "$loadingText : ${GREEN}FINISHED${NC}"
}

if [ "$2" = "pgv" ] || [ "$2" = "all" ]
then
  $p/res/pgv/compile "$3" & showLoading "Compiling .proto-files with protoc+pgv and generating tests"
fi

if [ "$2" = "vanilla" ] || [ "$2" = "all" ]
then
  $p/res/vanilla/compile "$3" & showLoading "Compiling .proto-files with protoc"
fi

if [ "$4" = "x64" ] || [ "$4" = "arm" ] || [ "$4" = "all" ]
then
  if [ "$3" = "go" ] || [ "$3" = "all" ]
  then
    $p/res/go/compile "$4" & showLoading "Compiling Go"
  fi

  if [ "$3" = "cpp" ] || [ "$3" = "all" ]
  then
    $p/res/cpp/compile "$4" & showLoading "Compiling C++"
  fi
fi

if [ "$1" = "perfy" ] || [ "$1" = "all" ]
then
  if ([ "$4" = "x64" ] && [ "$4" = "arm" ]) || [ "$4" = "all" ]
  then
    env GOOS=linux GOARCH=amd64 go build -o $p/out/x64/perfy $p/perfy.go & env GOOS=linux GOARCH=arm GOARM=7 go build -o $p/out/arm/perfy $p/perfy.go & showLoading "Compiling perfy.go"
  elif [ "$4" = "x64" ]
  then
    env GOOS=linux GOARCH=amd64 go build -o $p/out/x64/perfy $p/perfy.go & showLoading "Compiling perfy.go"
  elif [ "$4" = "arm" ]
  then
    env GOOS=linux GOARCH=arm GOARM=7 go build -o $p/out/arm/perfy $p/perfy.go & showLoading "Compiling perfy.go"
  fi
fi

if ([ "$4" = "arm" ] || [ "$4" = "all" ]) && [ "$5" != "" ]
then
  echo "Copying binary to remote (need pw)..."
  first=$(echo "$5" | cut -d: -f1)
  second=$(echo "$5" | cut -d: -f2)
  scp $p/out/arm/perfy "$first:$second/out/arm/perfy"
  cat << EOF > $p/out/arm/perfy.remote
#!/usr/bin/env bash
test=\$(echo "\$@" | grep -o "\-t .*" | cut -d" " -f2)
lang=\$(echo "\$@" | grep -o "\-l .*" | cut -d" " -f2)
echo "Copying test (need pw)..."
scp $p/res/\$lang/out/arm/\$test $first:$second/res/\$lang/out/arm/\$test
echo "Executing command (need pw)..."
ssh $first "$second/out/arm/perfy \$@ && rm $second/res/\$lang/out/arm/\$test"
EOF
  chmod +x $p/out/arm/perfy.remote
fi
