#!/usr/bin/env bash
p=$(cd $(dirname $BASH_SOURCE[0]); pwd -P)

# Small
g++ -std=c++11 -o $p/out/x64/SerializeSmall -Wall SerializeSmall.cpp ../pgv/gen/cpp/small.pb.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
g++ -std=c++11 -o $p/out/x64/DeserializeSmall -Wall DeserializeSmall.cpp ../pgv/gen/cpp/small.pb.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
g++ -std=c++11 -o $p/out/x64/ValidateSmall -Wall ValidateSmall.cpp ../pgv/gen/cpp/small.pb.cc ../pgv/gen/cpp/small.pb.validate.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/messages.pb.validate.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread

# Medium
g++ -std=c++11 -o $p/out/x64/SerializeMedium -Wall SerializeMedium.cpp ../pgv/gen/cpp/medium.pb.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
g++ -std=c++11 -o $p/out/x64/DeserializeMedium -Wall DeserializeMedium.cpp ../pgv/gen/cpp/medium.pb.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
g++ -std=c++11 -o $p/out/x64/ValidateMedium -Wall ValidateMedium.cpp ../pgv/gen/cpp/medium.pb.cc ../pgv/gen/cpp/medium.pb.validate.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/messages.pb.validate.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread

# Large
g++ -std=c++11 -o $p/out/x64/SerializeLarge -Wall SerializeLarge.cpp ../pgv/gen/cpp/large.pb.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
g++ -std=c++11 -o $p/out/x64/DeserializeLarge -Wall DeserializeLarge.cpp ../pgv/gen/cpp/large.pb.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
g++ -std=c++11 -o $p/out/x64/ValidateLarge -Wall ValidateLarge.cpp ../pgv/gen/cpp/large.pb.cc ../pgv/gen/cpp/large.pb.validate.cc ../pgv/gen/cpp/messages.pb.cc ../pgv/gen/cpp/messages.pb.validate.cc ../pgv/gen/cpp/validate/validate.pb.cc -I ~/.local/include -Wl,-Bstatic -L ~/.local/lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread

#!/usr/bin/env bash
p=$(cd $(dirname $BASH_SOURCE[0]); pwd -P)

arm_tools=/app/rbs/wrtools/tools-sdk-20160517/usr/bin/arm-wrs-linux-gnueabi

x64_include=$HOME/.local/include
arm_include=$HOME/.local/include_arm

x64_lib=$HOME/.local/lib
arm_lib=$HOME/.local/lib_arm

mkdir -p $p/out/x64
mkdir -p $p/out/arm/debug

for source_file in $p/*.cc
do
  source_name=$(echo $source_file | sed "s/.*\///" | sed "s/\.cc//")
  source_type=$(echo $source_name | sed "s/^[A-Z]a-z+])//" | perl -pe "s/[A-Z][a-z\d]*\K.*//" | sed "s/.*/\L&/" )

  source_proto_file=$p/../pgv/gen/cpp/$source_type.pb.cc
  source_validate_file=$p/../pgv/gen/cpp/$source_type.pb.validate.cc
  general_validate_file=$p/../pgv/gen/cpp/validate/validate.pb.cc

  x64_binary_file=$p/out/x64/$source_name
  arm_binary_file=$p/out/arm/$source_name
  arm_debug_file=$p/out/arm/debug/$source_name.debug_info

  if [ "$1" = "x64" ] || [ "$1" = "all" ]
  then
    # x86_64 compile
    g++ -std=c++11 -o$x64_binary_file -g -Wall "$source_file" $source_proto_file $source_validate_file $general_validate_file -I$x64_include -Wl,-Bstatic -L$x64_lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
  fi

  if [ "$1" = "arm" ] || [ "$1" = "all" ]
  then
    # arm compile
    $arm_tools/arm-wrs-linux-gnueabi-g++ -std=c++11 -o$arm_binary_file -fno-omit-frame-pointer -fasynchronous-unwind-tables --sysroot /proj/rbsNodeIfStorage/nodeif/DISTRO_CXA11448/R18G13/arm-wr6/ -g -Wall -lrt $source_file $source_proto_file $source_validate_file $general_validate_file -I $arm_include -Wl,-Bstatic -L$arm_lib -lprotobuf -Wl,-Bdynamic -pthread -lpthread
    # arm other
    $arm_tools/arm-wrs-linux-gnueabi-objcopy --only-keep-debug $arm_binary_file $arm_debug_file
    $arm_tools/arm-wrs-linux-gnueabi-strip --strip-debug --strip-unneeded $arm_binary_file
    $arm_tools/arm-wrs-linux-gnueabi-objcopy --add-gnu-debuglink=$arm_debug_file $arm_binary_file
  fi
done

