#!/usr/bin/env bash
p=$(cd $(dirname $BASH_SOURCE[0]); pwd -P)

if [ "$1" == "go" ] || [ "$1" == "all" ]
then
  protoc -I $p --go_out=$p/gen/go $p/*.proto
fi

if [ "$1" == "cpp" ] || [ "$1" == "all" ]
then
  protoc -I $p --cpp_out=$p/gen/cpp $p/*.proto
fi
